//////////////////////////////////////////////////////////////////
//do testowania POST, PUT i DELETE dla userow
//////////////////////////////////////////////////////////////////

### Get all users
GET http://localhost:8080/api/users


### Create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "test_user",
  "password": "test123",
  "role": "EMPLOYEE"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "test_user",
  "password": "test123"
}


### Update user
PUT http://localhost:8080/api/users/5
Content-Type: application/json

{
  "username": "updated_test_user",
  "password": "newpass123",
  "role": "ADMIN"
}


### Delete user
DELETE http://localhost:8080/api/users/5

/////////////////////////////////////////////////////////////////////
//testy taskow
/////////////////////////////////////////////////////////////////////

### Get all tasks
GET http://localhost:8080/api/tasks


### Create task
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "projectId": 1,
  "name": "Test task",
  "description": "Created from HTTP Client",
  "status": "TODO",
  "assignedUserIds": [1, 2]
}


### Update task
PUT http://localhost:8080/api/tasks/3
Content-Type: application/json

{
  "projectId": 1,
  "name": "Updated test task",
  "description": "Updated from HTTP Client",
  "status": "IN_PROGRESS",
  "assignedUserIds": [2]
}


### Delete task
DELETE http://localhost:8080/api/tasks/3
